apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sportsday-ingress
  namespace: sportsday
  nginx.ingress.kubernetes.io/ssl-redirect: "false"
  nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - host: "sportsday.edu.h.nc-toyama.ac.jp"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: panel-service
                port:
                  number: 80
    - host: "admin.sportsday.edu.h.nc-toyama.ac.jp"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: admin-service
                port:
                  number: 80
    - host: "api.sportsday.edu.h.nc-toyama.ac.jp"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: backend-service
                port:
                  number: 80
