apiVersion: v1
kind: PersistentVolume
metadata:
  name: sportsday-pv
  namespace: sportsday
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/dm-0/sportsday
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sportsday-mysql-pvc
  namespace: sportsday
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual